---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: myBluefin
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx-nvidia-open
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      cleanup: true
      copr:
        - iucar/rstudio

    install:
      packages:
        - fish
        - tmux
        - kmymoney
        - micro
        - python3-pip
        - r
        - rstudio
        - fontawesome-fonts-all
        - freetype-devel
        - fribidi-devel
        - zsh
        - java-latest-openjdk-devel
        - gcc
        - gcc-c++
        - gcc-gfortran
        - clang
        - llvm
        - sqlitebrowser
        - lftp
        - libcurl-devel
        - libjpeg-turbo-devel
        - libpng-devel
        - libtiff-devel
        - llvm-devel
        - meson
        - micro
        - tcl8-devel
        - tk8-devel
        - typescript

  - type: default-flatpaks
    system:
      install:
        - com.jeffser.Alpaca
        - dev.zed.Zed-Preview
        - io.github.benini.scid
        - io.github.shiftey.Desktop  # github desktop

  - type: gnome-extensions
    install:
      - Forge

  - type: rpm-ostree
    install:
      - https://cdn.insynchq.com/builds/linux/3.9.6.60027/insync-3.9.6.60027-fc42.x86_64.rpm

  # - type: rpm-ostree
  #   repos:
  #     - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
  #   install:
  #     - micro
  #     - duf
  #     - fish
  #     - gcc
  #   remove:
  #     # example: removing firefox (in favor of the flatpak)
  #     # "firefox" is the main package, "firefox-langpacks" is a dependency
  #     - firefox
  #     - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  # - type: default-flatpaks
  #   notify: true # Send notification after install/uninstall is finished (true/false)
  #   system:
  #     # If no repo information is specified, Flathub will be used by default
  #     install:
  #       - org.mozilla.firefox
  #       - org.gnome.Loupe
  #     remove:
  #       - org.gnome.eog
  #   user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
